// react/src/App.tsx
import * as React from 'react';
import {ChangeEvent} from 'react';
import FlatList from 'flatlist-react';
import {useClientStore} from 'client-web-storage/helpers/use-client-store';
import {useAppState} from 'client-web-storage/helpers/use-app-state';
import {Todo, TodoStatus} from './service/todo.service';
import {confirmAction, promptInput} from './utils';
import {TodoItem} from './components/todo-item';
import './style.scss';
import {StoreNames} from "./stores";
import {AppStateNames, AppStateType} from "./states";

export default function App() {
	// simply connect to your store with "useClientStore" hook
	// it will return the store state object to work with
	const todoStore = useClientStore<Todo>(StoreNames.Todo);
	const {state, setState} = useAppState<AppStateType>(AppStateNames.App);
	
	const updateSearchTerm = (event: ChangeEvent<HTMLInputElement>) => {
		setState({
			searchTerm: event.target.value
		});
	};
	
	const createTodo = async () => {
		const name = promptInput('Enter Todo Name:');
		
		if (name && name.trim().length) {
			try {
				// when performing actions, simply interact with the store directly
				// it is the interface to your server and storage APIs
				await todoStore.createItem({
					name,
				});
			} catch (e) {
				// you can handle error locally
				// or listen/subscribe to the ERROR event
				// or simply react to the "error" from using the "useClientStore" hook
				console.error(e);
			}
		}
	};
	
	const completeTodo = (todoId: string, completed: boolean) => {
		todoStore.updateItem(todoId, {
			status: completed ? TodoStatus.InProgress : TodoStatus.Completed,
		});
	};
	
	const markTodoDeleted = (todoId: string) => {
		todoStore.updateItem(todoId, {
			status: TodoStatus.Deleted,
		});
	};
	
	const deleteTodo = (todoId: string, todoName: string) => {
		const confirmed = confirmAction(
			`Are you sure you want to permanently delete "${todoName}" todo? This action cannot be reverted!`
		);
		
		if (confirmed) {
			todoStore.removeItem(todoId);
		}
	};
	
	const restoreTodo = (todoId: string) => {
		todoStore.updateItem(todoId, {
			status: TodoStatus.InProgress,
		});
	};
	
	const editName = (todoId: string, todoName: string) => {
		const newName = promptInput('Update name', todoName);
		
		if (newName && newName.trim().length) {
			todoStore.updateItem(todoId, {
				name: newName,
			});
		}
	};
	
	const editDescription = (todoId: string, todoDescription: string) => {
		const newDescription = promptInput('Update Description', todoDescription);
		
		if (newDescription && newDescription.trim().length) {
			todoStore.updateItem(todoId, {
				description: newDescription,
			});
		}
	};
	
	const renderTodo = (todo: Todo) => (
		<TodoItem todo={todo} key={todo.id}
		          onCompleteTodo={() => completeTodo(todo.id, todo.status === TodoStatus.Completed)}
		          onMarkTodoDeleted={() => markTodoDeleted(todo.id)}
		          onDeleteTodo={() => deleteTodo(todo.id, todo.name)}
		          onRestoreTodo={() => restoreTodo(todo.id)}
		          onEditName={() => editName(todo.id, todo.name)}
		          onEditDescription={() => editDescription(todo.id, todo.description)}
		/>
	);
	
	const renderBlank = () => {
		if (todoStore.error) {
			return <div className="error-message">{todoStore.error.message}</div>;
		}
		
		if (todoStore.loadingItems) {
			return <div className="loading-indicator">Loading...</div>;
		}
		
		if (state.searchTerm) {
			return <p>No items matched "{state.searchTerm}"</p>;
		}
		
		return (
			<div className="blank-status">
				<p>No Todo Items Yet!</p>
				<button type="button" onClick={createTodo} className="cta">
					Create Todo
				</button>
			</div>
		);
	};
	
	return (
		<div>
			<header>
				<h1>Todo Management App</h1>
				{todoStore.items.length ? (
					<div className="app-actions">
						<input
							type="search"
							placeholder="Search..."
							value={state.searchTerm}
							onChange={updateSearchTerm}
						/>
						<button type="button" onClick={createTodo} className="btn sm">
							Create
						</button>
					</div>
				) : (
					''
				)}
			</header>
			<hr/>
			<main className="list-container">
				{/* FlatList is a swiss knife of handling lists with many useful operations which saves us time */}
				<FlatList
					list={todoStore.items}
					renderItem={renderTodo}
					renderWhenEmpty={renderBlank}
					display={{
						row: true,
						rowGap: '20px'
					}}
					search={{
						term: state.searchTerm,
						by: ['name', 'description'],
						caseInsensitive: true,
						minCharactersCount: 2
					}}
					sort={{
						by: 'status',
					}}
					group={{
						by: (todo) =>
							todo.status === TodoStatus.Deleted
								? 'Deleted Todos'
								: 'Active Todos',
						separator: (group, idx, groupLabel) => (
							<h2 className="todos-section-title">
								{groupLabel} ({group.length})
							</h2>
						),
						sortedBy: 'status',
						sortedDescending: false
					}}
				/>
			</main>
		</div>
	);
}

// angular/src/app/app.component.ts
import {
  Component,
  ViewEncapsulation,
  OnInit,
  OnDestroy,
  ChangeDetectionStrategy,
  ChangeDetectorRef
} from '@angular/core';
import { UnSubscriber, StoreState } from 'client-web-storage';
import {
  withClientStore,
  DefaultStoreState,
} from 'client-web-storage/helpers/with-client-store';
import { Todo, TodoStatus } from './service/todo.service';
import { todoStore } from './stores/todo.store';
import {confirmAction, promptInput} from './utils';

interface TodoItems {
  active: Todo[],
  inactive: Todo[]
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AppComponent implements OnInit, OnDestroy {
  $todo: StoreState<Todo> = DefaultStoreState;
  todoItems: TodoItems = {active: [], inactive: []};
  searchTerm = '';
  $unsubscribeFromTodoStore: UnSubscriber = () => {};

  constructor(private cd: ChangeDetectorRef) {
    console.log(this.cd);
  }

  get hasTodos() {
    return this.todoItems.active.length > 0 || this.todoItems.inactive.length > 0;
  }
  ngOnInit() {
    this.$unsubscribeFromTodoStore = withClientStore<Todo>(
      todoStore,
      (data) => {
        this.$todo = data;
        this.filterAndGroupItems();
      }
    );
  }

  ngOnDestroy() {
    this.$unsubscribeFromTodoStore();
  }

  updateSearchTerm(value = this.searchTerm) {
    this.searchTerm = value;
    this.filterAndGroupItems();
  }

  filterAndGroupItems = () => {
    const searchPattern = new RegExp(this.searchTerm, 'i');

    this.todoItems = this.$todo.items
      .reduce((acc, todo) => {
        if (
          !this.searchTerm.trim().length ||
          (todo.name.search(searchPattern) > 0 || todo.description.search(searchPattern) > 0)
        ) {
          if(todo.status === TodoStatus.Deleted) {
            // @ts-ignore
            acc.inactive.push(todo)
          } else {
            // @ts-ignore
            acc.active.push(todo);
            acc.active = acc.active.sort((a, b) => {
              if (a.status === TodoStatus.Completed) {
                  return 1
              }

              return -1;
            })
          }
        }

        return acc;
      }, {active: [], inactive: []} as TodoItems);

    this.cd.detectChanges()
  }

  createTodo = async () => {
    const name = promptInput('Enter Todo Name:');

    if (name && name.trim().length) {
      todoStore.createItem({
        name,
      });
    }
  };

  completeTodo = (todoId: string, completed: boolean) => {
    todoStore.updateItem(todoId, {
      status: completed ? TodoStatus.InProgress : TodoStatus.Completed,
    });
  };

  markTodoDeleted = (todoId: string) => {
    todoStore.updateItem(todoId, {
      status: TodoStatus.Deleted,
    });
  };

  deleteTodo = (todoId: string, todoName: string) => {
    const confirmed = confirmAction(
      `Are you sure you want to permanently delete "${todoName}" todo? This action cannot be reverted!`
    );

    if (confirmed) {
      todoStore.removeItem(todoId);
    }
  };

  restoreTodo = (todoId: string) => {
    todoStore.updateItem(todoId, {
      status: TodoStatus.InProgress,
    });
  };

  editName = (todoId: string, todoName: string) => {
    const newName = promptInput('Update name', todoName);

    if (newName && newName.trim().length) {
      todoStore.updateItem(todoId, {
        name: newName,
      });
    }
  };

  editDescription = (todoId: string, todoDescription: string) => {
    const newDescription = promptInput(
      'Update Description',
      todoDescription
    );

    if (newDescription && newDescription.trim().length) {
      todoStore.updateItem(todoId, {
        description: newDescription,
      });
    }
  };
}

<div>
  <header>
    <h1>Todo Management App</h1>
    <div class="app-actions" *ngIf="hasTodos">
      <input
        type="search"
        placeholder="Search..."
        [ngModel]="searchTerm"
        (ngModelChange)="updateSearchTerm($event)"
      />
      <button type="button" (click)="createTodo()" class="btn sm">
        Create
      </button>
    </div>
  </header>
  <hr />
  <main class="list-container">
    <!-- Blank status -->
    <ng-container *ngIf="!hasTodos">
      <p *ngIf="searchTerm.length">No items matched "{{ searchTerm }}"</p>
      <div *ngIf="!searchTerm.length" class="blank-status">
        <p>No Todo Items Yet!</p>
        <button type="button" (click)="createTodo()" class="cta">
          Create Todo
        </button>
      </div>
    </ng-container>

    <!-- Active Todos -->
    <ng-container *ngIf="todoItems.active.length">
      <h2 class="todos-section-title">
        Active Todos ({{ todoItems.active.length }})
      </h2>
      <todo-item
        *ngFor="let todo of todoItems.active"
        [todo]="todo"
        (completeTodo)="completeTodo(todo.id, todo.status === 1)"
        (deleteTodo)="deleteTodo(todo.id, todo.name)"
        (markTodoDeleted)="markTodoDeleted(todo.id)"
        (editName)="editName(todo.id, todo.name)"
        (editDescription)="editDescription(todo.id, todo.description)"
        (restoreTodo)="restoreTodo(todo.id)"
      ></todo-item>
    </ng-container>

    <!-- Inactive Todos -->
    <ng-container *ngIf="todoItems.inactive.length">
      <h2 class="todos-section-title">
        Deleted Todos ({{ todoItems.inactive.length }})
      </h2>
      <todo-item
        *ngFor="let todo of todoItems.inactive"
        [todo]="todo"
      ></todo-item>
    </ng-container>
  </main>
</div>
