// angular/src/app/components/todo-item/todo-item.component.ts
import {ChangeDetectionStrategy, Component, Input, OnInit} from '@angular/core';
import { confirmAction, promptInput } from '../../utils';
import { Todo, TodoStatus } from '../../service/todo.service';
import { todoStore } from '../../stores/todo.store';

@Component({
  selector: 'todo-item[todo]',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class TodoItem {
  // @ts-ignore strictPropertyInitialization not having effect - this input is required by the component to work, so it should never have no value
  @Input() todo: Todo;

  get completed() {
    return this.todo?.status === TodoStatus.Completed;
  }

  get deleted() {
    return this.todo?.status === TodoStatus.Deleted;
  }

  get statusLabel() {
    return this.completed
      ? 'Completed'
      : this.deleted
      ? 'Deleted'
      : 'In Progress';
  }

  get statusCls() {
    return this.completed
      ? 'completed'
      : this.deleted
      ? 'deleted'
      : 'in-progress';
  }

  completeTodo = () => {
    todoStore.updateItem(this.todo.id, {
      status: this.completed ? TodoStatus.InProgress : TodoStatus.Completed,
    });
  };

  markTodoDeleted = () => {
    todoStore.updateItem(this.todo.id, {
      status: TodoStatus.Deleted,
    });
  };

  deleteTodo = () => {
    const confirmed = confirmAction(
      `Are you sure you want to permanently delete "${this.todo?.name}" todo? This action cannot be reverted!`
    );

    if (confirmed) {
      todoStore.removeItem(this.todo.id);
    }
  };

  restoreTodo = () => {
    todoStore.updateItem(this.todo.id, {
      status: TodoStatus.InProgress,
    });
  };

  editName = () => {
    const newName = promptInput('Update name', this.todo?.name);

    if (newName && newName.trim().length) {
      todoStore.updateItem(this.todo.id, {
        name: newName,
      });
    }
  };

  editDescription = () => {
    const newDescription = promptInput(
      'Update Description',
      this.todo?.description
    );

    if (newDescription && newDescription.trim().length) {
      todoStore.updateItem(this.todo.id, {
        description: newDescription,
      });
    }
  };
}

<div class="todo-item">
  <h3>
    <strong [class]="'status ' + statusCls ">{{statusLabel}}</strong>
    <span (click)="editName()">
      {{todo.name}}
    </span>
  </h3>
  <p class="description" (click)="editDescription()">
    {{todo.description}}
  </p>
  <div class="actions">
    <ng-container *ngIf="deleted">
      <button
        *ngIf="deleted"
        type="button"
        (click)="markTodoDeleted()"
        class="btn sm outline"
      >
        Restore
      </button>
      <button
        *ngIf="deleted"
        type="button"
        (click)="restoreTodo()"
        class="btn sm outline"
      >
        Permanently Delete
      </button>
    </ng-container>
    <ng-container *ngIf="!deleted">
      <button type="button" (click)="completeTodo()" class="btn sm cta">
        {{completed ? 'Move in Progress' : 'Mark as Done'}}
      </button>
      <button
        type="button"
        (click)="deleteTodo()"
        class="btn sm outline"
      >
        Delete
      </button>
    </ng-container>
  </div>
</div>

// react/src/components/todo-item.tsx
import * as React from 'react';
import { Fragment } from 'react';
import { todoStore } from '../stores/todo.store';
import { Todo, TodoStatus } from '../service/todo.service';
import { promptInput, confirmAction } from '../utils';
import './todo-item.scss';

export interface TodoItemProps {
  todo: Todo;
}

/**
 * the TodoItem is free to interact with the store which will trigger
 * the rigth API calls and data update focusing only the business logic
 * related to the UI rather than working with data and API inside the component
 */
export const TodoItem = ({ todo }: TodoItemProps) => {
  const completed = todo.status === TodoStatus.Completed;
  const deleted = todo.status === TodoStatus.Deleted;
  const statusLabel = completed
    ? 'Completed'
    : deleted
    ? 'Deleted'
    : 'In Progress';
  const statusCls = completed
    ? 'completed'
    : deleted
    ? 'deleted'
    : 'in-progress';

  const completeTodo = () => {
    todoStore.updateItem(todo.id, {
      status: completed ? TodoStatus.InProgress : TodoStatus.Completed,
    });
  };

  const markTodoDeleted = () => {
    todoStore.updateItem(todo.id, {
      status: TodoStatus.Deleted,
    });
  };
  
  const deleteTodo = () => {
    const confirmed = confirmAction(
      `Are you sure you want to permanently delete "${todo.name}" todo? This action cannot be reverted!`
    );
    
    if (confirmed) {
      todoStore.removeItem(todo.id);
    }
  };

  const restoreTodo = () => {
    todoStore.updateItem(todo.id, {
      status: TodoStatus.InProgress,
    });
  };

  const editName = () => {
    const newName = promptInput('Update name', todo.name);

    if (newName && newName.trim().length) {
      todoStore.updateItem(todo.id, {
        name: newName,
      });
    }
  };

  const editDescription = () => {
    const newDescription = promptInput('Update Description', todo.description);

    if (newDescription && newDescription.trim().length) {
      todoStore.updateItem(todo.id, {
        description: newDescription,
      });
    }
  };

  return (
    <div className="todo-item">
      <h3>
        <strong className={`status ${statusCls}`}>{statusLabel}</strong>
        <span onClick={editName}>
          {todo.name}
        </span>
      </h3>
      <p className="description" onClick={editDescription}>
        {todo.description}
      </p>
      <div className="actions">
        {deleted ? (
          <Fragment>
            <button
              type="button"
              onClick={restoreTodo}
              className="btn sm"
            >
              Restore
            </button>
            <button
              type="button"
              onClick={deleteTodo}
              className="btn sm outline"
            >
              Delete Permanently
            </button>
          </Fragment>
        ) : (
          <Fragment>
            <button type="button" onClick={completeTodo} className="btn sm cta">
              {completed ? 'Move in Progress' : 'Mark as Done'}
            </button>
            <button
              type="button"
              onClick={markTodoDeleted}
              className="btn sm outline"
            >
              Delete
            </button>
          </Fragment>
        )}
      </div>
    </div>
  );
};
